# Generated by Django 4.0 on 2022-01-02 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.CharField(default='https://media-exp1.licdn.com/dms/image/C511BAQFDjtrS0u76Tw/company-background_10000/0/1585488022941?e=1641214800&v=beta&t=7-RygNRYRMFQVUc3_WeXIQNWwX-u46UAEoR-ooMWqEY', max_length=511, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='hasQuota',
            field=models.BooleanField(default=False),
        ),
    ]
