# Generated by Django 4.0 on 2022-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.CharField(default='https://bevents.co/wp-content/uploads/2020/02/events.jpg', max_length=511, verbose_name='picture'),
        ),
    ]
