# Generated by Django 4.0 on 2022-01-01 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        ('service', '0002_initial'),
        ('user', '0002_rename_issuperuser_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, null=True, related_name='feedbacks', to='feedback.Feedback'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='userFollowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ManyToManyField(related_name='services', to='service.Service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(default='Newcomer', max_length=255, verbose_name='badge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.CharField(default='https://www.pngall.com/wp-content/uploads/5/Profile-PNG-Clipart.png', max_length=511, verbose_name='profile picture'),
        ),
    ]
