# Generated by Django 4.0 on 2022-01-02 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_taker'),
        ('user', '0005_alter_user_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, related_name='feedbacks', to='feedback.Feedback'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='userFollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
