# Generated by Django 4.0 on 2022-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_requests'),
        ('user', '0006_alter_user_feedbacks_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='services', to='service.Service'),
        ),
    ]
