# Generated by Django 4.0 on 2021-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.CharField(max_length=511, verbose_name='comment')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
