# Generated by Django 4.0 on 2021-12-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('service', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_giver', to='user.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='service.service'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_taker', to='user.user'),
        ),
    ]
