# Generated by Django 4.0 on 2022-01-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_service'),
        ('feedback', '0004_alter_feedback_taker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='taker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_taker', to='user.user'),
        ),
    ]
