# Generated by Django 4.0 on 2022-01-02 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_service_feedbackgiven_service_picture_service_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
