# Generated by Django 4.0 on 2022-01-07 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_alter_service_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='taker',
        ),
        migrations.AddField(
            model_name='service',
            name='taker',
            field=models.ManyToManyField(blank=True, null=True, related_name='takers', to=settings.AUTH_USER_MODEL),
        ),
    ]
