# Generated by Django 4.0 on 2022-01-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_taker'),
        ('service', '0006_alter_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='feedbackGiven',
        ),
        migrations.AddField(
            model_name='service',
            name='feedbackList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbackList', to='feedback.feedback'),
        ),
    ]
